# Introduction to Numpy and Matplotlib
Numpy is a library for scientific computing in Pyhton. In this part of the course you will learn to:
 * create and display one- and multi-dimensional arrays
 * load real experimental data from files into arrays
 * use built-in Numpy functions to analyse the data
 * use the Matplotlib library to display the results
 * manipulate the arrays to change their shape and size
 
 So let's start! :)

The main numpy object is called an array. An array is a collection of items of the same type. For the start, you can imagine the array as a table of numbers. The catch is: an array is a multidimensional object. We will soon learn what this means.
To use numpy, we need to _import_ the module. This is done by writing the following at the top of our code:

In [1]:
import numpy as np

# Array creation
There are many ways to create an array, depending on the purpose. One of the most common ones is np.arange(N), which gives us a 1-D array with N elements, starting from 0 to N-1.  

In [2]:
A = np.arange(20)
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


If we need non-integers or a certain spacing between the elements, we use np.linspace() which linearly interpolates
between the start and the end element. 

In [5]:
start_element = 0
end_element = 4
tot_no_elements = 10

B = np.linspace(start_element, end_element, tot_no_elements)
print (B)

[ 0.          0.44444444  0.88888889  1.33333333  1.77777778  2.22222222
  2.66666667  3.11111111  3.55555556  4.        ]


Let's print individual elements or desired range of elements.

In [6]:
print (B[1]) # notice that the indexing starts from zero!
print (B[3:5])
print(B[:-1]) # numpy can also count backwards, -1 is the last element!

0.444444444444
[ 1.33333333  1.77777778]
[ 0.          0.44444444  0.88888889  1.33333333  1.77777778  2.22222222
  2.66666667  3.11111111  3.55555556]


Let's create some multidimensional arrays and see how to work with them.

In [11]:
C = np.arange(16).reshape(4,4)
print(C)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [15]:
D =  np.arange(15).reshape(3,5)
print(D)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


The dimensions of a numpy array are called axes. The number of dimensions (axes) is called a rank. To see the number of dimensions of the array, we use np.ndim(). To see the length of each dimension, we use np.shape().

In [17]:
print ('Number of dimensions')
print(np.ndim(C))
print(np.ndim(D))

print ('Shape of the arrays')
print(np.shape(C))
print(np.shape(D))

Number of dimensions
2
2
Shape of the arrays
(4, 4)
(3, 5)


Numpy is a very powerful tool and indexing can be confusing for a beginner. If you get lost, remember to always print
your result and check if it makes sense. Let's print some elements from our array D.

In [21]:
print(D[1, 2]) # element in the row number 1 (start counting from zero!)

7


## TO FINISH TODAY (Fri 17 Nov)
**examples:**
 * loading in the array from data example
 * plotting example (sine function or something super easy) in Matplotlib, basic mode
 
 **exercise for them (no given solution prior to them solving):**
 * loading in Michaels's real neuro data as array (i might put it to .txt instead of .xslx to ease up)
 * printing the properties of this array (length, ndim, shape..)
 * plotting the array
 
 **-> HERE COMES JASON'S PART WITH THRESHOLDING AND ANALYSIS**